### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by Shuaa11** [Mohido/Ragnarok_Madness_Game#30]

**Comment by Mohido** [comment]
@Shuaa11  You will be using JUnit right? can you also write the script in which it will run the test cases, please?

**Comment by Shuaa11** [comment]
Yes I am using JUnit version 5 for the test cases. Ok I will write the script.

**Comment by Mohido** [comment]
I think this issue should be closed right now. If you think you are totally done from this issue @Shuaa11 . Then go ahead and close it.

**Comment by Shuaa11** [comment]
Yes. I am done writing the test cases. I have linked the pull request as well. I am closing the issue now.
