### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by Shuaa11** [Mohido/Ragnarok_Madness_Game#58]
Continuous deployment is regular and automatic, and the build artefact history (e.g. older versions) is available to users.

**Comment by Shuaa11** [comment]
The latest version of the project will be deployed to Google drive. Each artefact will contain the version name and the commit number as well. For the developer to be able to trace back to the commit where the CD was triggered. The user will be able to see the latest and older versions of the game as well.

**Comment by Mohido** [comment]
Okie that looks super fine. Please attach the pull request related to this commit later if you have time.

**Comment by Shuaa11** [comment]
The implementation is done and I have linked the pull-request related to this issue. The project will only deploy from a stable branch, that is the master branch. The Google Drive URL can be accessed in the CI job under "Output the Google drive link".
